export const authConstants = {
    UI_SET_AUTH_PHONE: "UI_SET_AUTH_PHONE",
    UI_SET_AUTH_OTP: "UI_SET_AUTH_OTP",
    UI_SET_AUTH_OTP_FORM: "UI_SET_AUTH_OTP_FORM",
    API_SEND_OTP: "API_SEND_OTP",
    API_VERIFY_OTP: "API_VERIFY_OTP",
    API_USER_DATA: "API_USER_DATA",
};