export const bookingConstants = {
    UI_SET_SELECTED_BOOKING: "UI_SET_SELECTED_BOOKING",
    UI_SET_CURRENT_BOOKING_PAGE: "UI_SET_CURRENT_BOOKING_PAGE",
    UI_SET_BOOKING_INITIAL_STATE: "UI_SET_BOOKING_INITIAL_STATE",
    UI_SET_INITIAL_CUSTOMER_DATA: "UI_SET_INITIAL_CUSTOMER_DATA",

    API_GET_BOOKING_LIST: "API_GET_BOOKING_LIST",
    API_GET_BOOKING_BY_ID: "API_GET_BOOKING_BY_ID",
    API_ADD_BOOKING: "API_ADD_BOOKING",
    API_UPDATE_BOOKING: "API_UPDATE_BOOKING",
    API_UPDATE_BOOKING_STATUS: "API_UPDATE_BOOKING_STATUS",
    API_CANCEL_SELECTED_BOOKING: "API_CANCEL_SELECTED_BOOKING",
    API_ADD_CUSTOMER_RESPONSE: "API_ADD_CUSTOMER_RESPONSE",
    API_GET_CUSTOMER_RESPONSE: "API_GET_CUSTOMER_RESPONSE"
};