export const commonConstants = {
    UI_SET_LOADING: "UI_SET_LOADING",
    UI_SET_COMMON_INITIAL_STATE: "UI_SET_COMMON_INITIAL_STATE",
    UI_SET_DIVISION_LOADING: "UI_SET_DIVISION_LOADING",
    UI_SET_PRODUCT_LOADING: "UI_SET_PRODUCT_LOADING",
    UI_SET_MODEL_UPDATE_LOADING: "UI_SET_MODEL_UPDATE_LOADING",
    UI_SET_PAYMENT_SETTING_LOADING: "UI_SET_PAYMENT_SETTING_LOADING",
    UI_SET_GOOGLE_ADDRESS: "UI_SET_GOOGLE_ADDRESS",

    API_UPDATE_STATUS: "API_UPDATE_STATUS"
};