export const excelProductConstants = {
    UI_SET_SELECTED_EXCEL_PRODUCT_LIST: "UI_SET_SELECTED_EXCEL_PRODUCT_LIST",
    UI_SET_CURRENT_EXCEL_PRODUCT_PAGE: "UI_SET_CURRENT_EXCEL_PRODUCT_PAGE",
    UI_SET_EXCEL_PRODUCT_INITIAL_STATE: "UI_SET_EXCEL_PRODUCT_INITIAL_STATE",

    API_GET_EXCEL_PRODUCT_LIST: "API_GET_EXCEL_PRODUCT_LIST",
    API_UPDATE_EXCEL_PRODUCT: "API_UPDATE_PRODUCT",
};