export const productModelConstants = {
    UI_SET_MODEL_DATA:"UI_SET_MODEL_DATA",
    UI_SET_MODEL_INITIAL_STATE: "UI_SET_MODEL_INITIAL_STATE",
    UI_SET_SELECTED_MODEL: "UI_SET_SELECTED_MODEL",
    UI_SET_CURRENT_MODEL_PAGE: "UI_SET_CURRENT_MODEL_PAGE",

    API_GET_PRODUCT_MODEL_LIST: "API_GET_PRODUCT_MODEL_LIST",
    API_GET_PRODUCT_MODEL_BY_ID: "API_GET_PRODUCT_MODEL_BY_ID",
    API_ADD_PRODUCT_MODEL: "API_ADD_PRODUCT_MODEL",
    API_UPDATE_PRODUCT_MODEL: "API_UPDATE_PRODUCT_MODEL",
    API_DELETE_PRODUCT_MODEL : "API_DELETE_PRODUCT_MODEL"
};