export const userConstants = {
    UI_SET_SELECTED_USER: "UI_SET_SELECTED_USER",
    UI_SET_CURRENT_USER_PAGE: "UI_SET_CURRENT_USER_PAGE",
    UI_SET_USER_INITIAL_STATE:"UI_SET_USER_INITIAL_STATE",

    API_GET_USER_LIST: "API_GET_USER_LIST",
    API_GET_USER_BY_ID: "API_GET_USER_BY_ID",
    API_ADD_USER: "API_ADD_USER",
    API_UPDATE_USER: "API_UPDATE_USER"
};